### ISSUE TITLE
Please fix dark theme on windows

### ISSUE THREAD

**Issue by Hadden89** [smplayer-dev/smplayer-themes#2]
**Describe the bug**
The default dark theme, while is very well made, have issue when "textual buttons" are add - like the ones for aspect ratio.

**To Reproduce**
Just add such buttons to the main toolbar.

**Expected behavior**
Text should be white/light gray

**Screenshots**
![smp](https://user-images.githubusercontent.com/18642541/111075153-ef799800-84e6-11eb-972e-ca4edb3db813.PNG)

**Your Enviroment**
 - Smplayer 21.1.0 (revisione 9475) 
 - Windows 10 20H2

**Additional context**
While I really hope this will be addressed, I could try to workaround this on my own. I know SMP use QSS for theming which is similar to CSS and I have some (basic) knowledge of that (I did a quick fix for a 18.x SMP theme in past). Just let me know what I need to do ;)

The same happens with links in about SMP.
![smp2](https://user-images.githubusercontent.com/18642541/111078188-9f093700-84f4-11eb-8ab8-0108f91bb3fa.PNG)

I know that usually text/link colors are inherited by the OS, but as the player use stylesheets should be easily override-able.

Tnx for the player and have a good time.

**Comment by smplayer-dev** [comment]
I think it's fixed now.
https://github.com/smplayer-dev/smplayer-themes/commit/14cea0b5ab71888868bce16c47fe0ef32be98edc

**Comment by Hadden89** [comment]
Tnx, I'll get the fixed one ;) I knew was very easy ^^,
